name: Security Audit

on:
  schedule:
    # Run weekly security scans
    - cron: '0 8 * * 1'
  push:
    branches: [ main, master, 'feature/**' ]
  workflow_dispatch:

jobs:
  security-scan:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit[toml] pip-audit

    - name: Audit dependencies with safety
      run: |
        python -m safety check --json --output safety-report.json || true

    - name: Audit dependencies with pip-audit
      run: |
        python -m pip_audit --desc --format=json --output=pip-audit-report.json || true

    - name: Static analysis with bandit
      run: |
        python -m bandit -r src -f json -o bandit-report.json || true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          pip-audit-report.json
          bandit-report.json

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate
